### PR TITLE
Upgrade to 3.13.1~ynh1

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Upgrade to 3.13.1~ynh1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by Josue-T** [comment]
Can you upgrade directly to the version 1.14 as it's the last version.

**Comment by yalh76** [comment]
> Can you upgrade directly to the version 1.14 as it's the last version.

I can't because last version is always available at `https://www.monitorix.org/monitorix_*****_all.deb`  but previous version are available at `https://www.monitorix.org/old-versions/monitorix_****_all.deb`

So if using the actual last version, when next version will be released by monitorix, current yunohost package will be broken,.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
will redo it from scratch

**Pull request closed without merging**
