### PR TITLE
Apply example_ynh

### LINKED ISSUE #27: source path not updated
Hello, the app can't be installed because the latest version is 3.13.1 and ynh 3.12, so the script doesn't find the source (3.12 was moved to /old-versions/ on the monitorix website.
Maybe a future script can check both paths so that an update doesn't break the install script.

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *[Apply last example_ynh](https://github.com/YunoHost-Apps/monitorix_ynh/commit/b9df8d590523f24b69c3aaff6ecf6dd39fb7ff53)*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by Josue-T** [comment]
Hello, did you test the upgrade from the old version with some data and check that on the upgrade nothing was lost ?

**Comment by yalh76** [comment]
> Hello, did you test the upgrade from the old version with some data and check that on the upgrade nothing was lost ?

Not for now, I will test after the package_check

**Comment by Josue-T** [comment]
As mentionned [here](https://github.com/YunoHost-Apps/monitorix_ynh/pull/26#issue-800780259) there are a issue about the upgrade from the old version, that I also had. So just rewriting the package wont fix this issue.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> As mentionned [here](https://github.com/YunoHost-Apps/monitorix_ynh/pull/26#issue-800780259) there are a issue about the upgrade from the old version, that I also had. So just rewriting the package wont fix this issue.

Removed upgrade to 3.13.1

**Comment by yalh76** [comment]
!testme

**Comment by Josue-T** [comment]
> > As mentionned [here](https://github.com/YunoHost-Apps/monitorix_ynh/pull/26#issue-800780259) there are a issue about the upgrade from the old version, that I also had. So just rewriting the package wont fix this issue.
> 
> Removed upgrade to 3.13.1

Well, I didn't wanted that you remove the upgrade. I just would like that you fix correctly this upgrade.

And about this refactoring did you test manually the upgrade from the previous package and check that everything is ok and that there are no data loss and no regression. Because after all of these refactoring like that I many time saw, some month after, some regression and after is me who need to fix the issue...

**Comment by Josue-T** [comment]
**Please don't merge the pull request if I didn't approved.** If you wan't to merge like this, be the maintainer of this package and assume all issues linked to this !!!!

**Comment by yalh76** [comment]
sorry, I won't

**Pull request merged**
